### ISSUE TITLE
Click events not recognized after bringing window into focus

### ISSUE THREAD

**Issue by frenchy64** [HumbleUI/HumbleUI#38]
On macOS Monterey.

![click-from-outside](https://user-images.githubusercontent.com/287396/188713437-a6eea145-7582-4627-b577-6313800aa608.gif)

**Comment by tonsky** [comment]
can you check on latest version? I think this might’ve been fixed in https://github.com/HumbleUI/HumbleUI/commit/0dce46864018b5c54b671016bc6c11afc2422cac

https://user-images.githubusercontent.com/285292/188976353-2aa25393-7319-4911-8d49-a7ddc064dd29.mov

**Comment by frenchy64** [comment]
Still the same behavior on my end on https://github.com/HumbleUI/HumbleUI/commit/91f43c3ad7ea0819f5dea99b54cfe61b9d8ae8c8. Any mouse behavior seems to be ignored after clicking into the window, including scrolling, and changing the cursor to `|` when mousing over a text box (until mouse move).

**Comment by frenchy64** [comment]
@tonsky I spent some time trying to diagnose: https://www.youtube.com/watch?v=SvuBhFUJUo0

Might be worth a watch on x2 speed. This part was the most surprising, where the events were firing but the x/y coords was somewhere to the left of the HumbleUI window. https://youtu.be/SvuBhFUJUo0?t=1409

**Comment by tonsky** [comment]
Very interesting indeed. It looks like you are not getting mousemove when window is inactive. In my case even in inactive window I get both mouse move and scroll. 

https://user-images.githubusercontent.com/285292/189448427-5ab9a433-f623-424b-ad57-28f154cae32f.mp4

I have two guesses: what version of macOS are you on, and how are you starting Humble UI?

One thing to try might be to run [JWM](https://github.com/humbleUI/jwm) demo (script/run.py) and see if you get move events on inactive window?

**Comment by frenchy64** [comment]
> I have two guesses: what version of macOS are you on, and how are you starting Humble UI?

macOS 12.5.1 (Intel macbook pro)

./script/run.py



> One thing to try might be to run [JWM](https://github.com/humbleUI/jwm) demo (script/run.py) and see if you get move events on inactive window?

Seems to be a similar problem with the first clicks being at the wrong coordinates.

https://user-images.githubusercontent.com/287396/189464370-ff3d2c41-a5b7-4938-9c5b-ba25052dce40.mp4

**Comment by tonsky** [comment]
Well, I guess the reason is your window is not getting mousemove events when not in focus. I have no idea why. Mine does :(

**Comment by tonsky** [comment]
I’d appreciate a lot if you were able to figure it out, since I can’t reproduce it. Let me know how I can help

**Comment by jdf-id-au** [comment]
Thanks for this amazing suite of software (incl JWM, Skija, ...).

I'm finding (on macOS both 13.1 x86 and 13.2.1 arm64) that `{:button :primary :pressed? true}` only occurs with a full trackpad click, not with the _Tap to click_ feature from _System Settings.app_. I had a quick look around HumbleUI and JWM and couldn't find why this might be. Can probably assist if you tell me what I need to do.

**Comment by frenchy64** [comment]
> I'm finding (on macOS both 13.1 x86 and 13.2.1 arm64) that {:button :primary :pressed? true} only occurs with a full trackpad click, not with the Tap to click feature from System Settings.app.

I also observed this behavior. I thought I was imagining it.

**Comment by tonsky** [comment]
I’ve seen it too. No idea why it’s happening, I’m not doing anything smart with AppKit API. Last time I tried to debug it, though, it disappeared :) I’ll give it another shot eventually
